### ISSUE TITLE
Something similar but in C# .NET

### ISSUE THREAD

**Issue by Sicos1977** [unixfreak0037/officeparser#11]
Hi,

I've made something similar in C# .NET... maybe it can be useful for you

https://github.com/Sicos1977/OfficeExtractor

Greetings,
Kees van Spelde

**Comment by dimmyr** [comment]
@Sicos1977, your .NET version does not extract macros, but only file objects.  Is it possible to create a functionality to do macros too?

**Comment by Sicos1977** [comment]
yes it is possible but that was not the goal of the project
