### ISSUE TITLE
Syntax error.

### ISSUE THREAD

**Issue by airyt** [unixfreak0037/officeparser#15]
howdy - trying to extract vb modules from a doc file. installed python 3.7.0a2 and am getting an error:
```
  File "C:\temp\officeparser.py", line 271
    print '{0:08X}'.format(sector)
                  ^
SyntaxError: invalid syntax

```

any help would be helpful!! thx, airyt

Edit: Windows 7

**Comment by PeterMueller4711** [comment]
I think its written in python 2.x ... maybe thats where this comes from.

**Comment by decalage2** [comment]
For python 3 you may use olevba3.py from oletools: https://github.com/decalage2/oletools
(It is based on officeparser)

**Comment by airyt** [comment]
I should've updated this issue, sorry. 
Yes, uninstalling python3 and installing python2 resolved this issue. will try p3 & the oletools next time. thanks.
